import * as THREE from "three";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import Box from "components/box";
import useWindowDimensions from "hooks/useWindowDimension";

export default function Home() {
  const { width, height } = useWindowDimensions();
  return (
    <>
      <Head>
        <title>CG Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.webGlDiv}>
          <Canvas>
            <ambientLight color="white" />
            <perspectiveCamera
              fov={45}
              aspect={width && height ? width / height : 1}
              near={0.1}
              far={1000}
              position={[0, 0, 0]}
            />
            <gridHelper />
            <Box />
          </Canvas>
        </div>
      </main>
    </>
  );
}
